DROP TABLE IF EXISTS Curso;
DROP TABLE IF EXISTS Turma;
DROP TABLE IF EXISTS Matricula;

CREATE TABLE Curso (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT UNIQUE NOT NULL,
    descricao TEXT NOT NULL  
);

CREATE TABLE Turma (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    curso_id INTEGER NOT NULL,
    nome TEXT UNIQUE NOT NULL,
    FOREIGN KEY (curso_id) REFERENCES Curso (id) 
);

CREATE TABLE Matricula (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    turma_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    FOREIGN KEY (turma_id) REFERENCES Turma (id)
);
